title: Leonel Aguilar
description: Leonel Aguilar, Senior Researcher at ETH Zürich. Building AI systems for humans through machine learning, behavioural science and engineering.
url: https://leaguilar.github.io
baseurl: ""
email: aleonel@ethz.ch
linkedin: https://www.linkedin.com/in/leonelaguilar/
timezone: Europe/Zurich
markdown: kramdown
permalink: /:categories/:title/
include: [_pages]
collections:
  research:
    output: true
plugins:
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md
  - _posts
  - _pages/home.md
  - _pages/year-archive.md
  - _pages/tag-archive.md
  - _pages/category-archive.md
  - assets/academicons-1.9.2
  - .bundle
  - .jekyll-cache
  - assets/cv.pdf
